name: Sync Fork

on:
  schedule:
    - cron: "*/10 * * * *" # every 10 minutes
#    - cron: '0 0 * * *' # At the end of every day
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          owner: openjdk
          base: foreign-jextract
          head: foreign-jextract
          auto_approve: true